import Link from "next/link";

const FAQ_SECTIONS = [
  {
    title: "Data Privacy & Security",
    items: [
      {
        q: "What data does Denali collect?",
        a: "We store only what's needed: your email (for login), conversation history, and appeal letters. If you connect Medicare via Blue Button, we cache your claims and coverage data (encrypted, refreshed every 24 hours). We never store your full name, address, SSN, or insurance ID.",
      },
      {
        q: "Is my health data encrypted?",
        a: "Yes. All Blue Button tokens are encrypted with AES-256-GCM before storage. Data in transit uses TLS 1.2+. Your cached health data is only accessible to your authenticated account.",
      },
      {
        q: "Who can see my data?",
        a: "Only you. Our AI processes your conversations to provide guidance, but we don't share individual data with third parties. Anonymized, de-identified patterns may be used to improve our recommendations.",
      },
    ],
  },
  {
    title: "How We Use Your Health Data",
    items: [
      {
        q: "What happens when I connect Medicare?",
        a: "We use CMS Blue Button 2.0 to fetch your coverage status, recent claims, and any denied claims. This lets our AI personalize guidance — for example, referencing your actual coverage instead of asking you to look it up.",
      },
      {
        q: "Can I control how my health data is used?",
        a: "Yes. In Settings > Privacy & Data, you can toggle whether your health data is used in AI conversations, whether it's cached locally, and whether you share anonymous usage analytics.",
      },
    ],
  },
  {
    title: "Consent & Preferences",
    items: [
      {
        q: "What consents do I need to give?",
        a: "Using Denali for coverage guidance requires no consent or account. For appeals, we need your email. For health data features, we ask for explicit consent before accessing or using your Medicare records in conversations.",
      },
      {
        q: "Can I revoke consent?",
        a: "Anytime. Go to Settings > Privacy & Data and toggle off any consent. If you revoke health data consent, we stop using it in conversations immediately. You can also disconnect Medicare entirely.",
      },
    ],
  },
  {
    title: "Medicare.gov Connection",
    items: [
      {
        q: "Is this connected to Medicare.gov?",
        a: "We use CMS Blue Button 2.0, the official Medicare API, to access your claims and coverage data with your permission. We're working toward deeper Medicare.gov integration as part of the CMS Health Technology Ecosystem.",
      },
    ],
  },
  {
    title: "Trial & Pricing",
    items: [
      {
        q: "Is Denali free?",
        a: "Coverage guidance is always free, unlimited, and requires no account. Your first 3 appeal letters are free (email verification required). After that, it's $10 per appeal or $25/month for unlimited appeals.",
      },
      {
        q: "Is there a free trial?",
        a: "Yes. Medicare beneficiaries can start a 30-day free trial with full access to all features including unlimited appeals.",
      },
    ],
  },
  {
    title: "Appeal Letters",
    items: [
      {
        q: "How accurate are the appeal letters?",
        a: "Our letters cite real LCD/NCD policy numbers, use correct ICD-10 and CPT codes, and include relevant clinical evidence from PubMed. However, they should be reviewed by you and your healthcare provider before submission.",
      },
      {
        q: "Does Denali guarantee my appeal will be approved?",
        a: "No. We provide the strongest possible letter based on Medicare policy, but approval depends on your specific medical situation, documentation, and the reviewer. Our guidance helps maximize your chances.",
      },
    ],
  },
  {
    title: "AI Disclosure",
    items: [
      {
        q: "Is this AI-generated content?",
        a: "Yes. All responses are generated by AI (Claude by Anthropic). Every message is clearly marked as AI-generated. Our guidance is based on real Medicare policies but does not replace clinical judgment.",
      },
      {
        q: "What are the limitations?",
        a: "Denali provides Medicare coverage guidance only — not medical advice, legal advice, or billing services. We focus on Original Medicare; Medicare Advantage plans have their own rules. Always verify with your healthcare provider.",
      },
    ],
  },
  {
    title: "Account & Deletion",
    items: [
      {
        q: "Can I delete my account?",
        a: "Yes. Go to Settings and request account deletion. We permanently delete all your data: conversations, appeals, health data, payment records, and authentication. This action cannot be undone.",
      },
      {
        q: "What data is retained after deletion?",
        a: "Only anonymized, de-identified learning data (like 'symptom X maps to code Y with Z% confidence'). No personally identifiable information is retained.",
      },
    ],
  },
  {
    title: "Accessibility",
    items: [
      {
        q: "Is Denali accessible?",
        a: "We follow WCAG guidelines: minimum 16px font size, adjustable text scaling, high contrast support, screen reader compatibility, and 44x44px minimum touch targets. Adjust text size in Settings > Accessibility.",
      },
    ],
  },
];

export default function FAQPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-2">
        Frequently Asked Questions
      </h1>
      <p className="text-[var(--text-secondary)] mb-10">
        How Denali handles your data, privacy, and Medicare guidance.
      </p>

      {FAQ_SECTIONS.map((section) => (
        <div key={section.title} className="mb-10">
          <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-4 pb-2 border-b border-[var(--border)]">
            {section.title}
          </h2>
          <div className="space-y-6">
            {section.items.map((item) => (
              <div key={item.q}>
                <h3 className="text-sm font-medium text-[var(--text-primary)] mb-1">
                  {item.q}
                </h3>
                <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                  {item.a}
                </p>
              </div>
            ))}
          </div>
        </div>
      ))}

      <div className="border-t border-[var(--border)] pt-6 mt-10">
        <p className="text-sm text-[var(--text-muted)]">
          Have more questions?{" "}
          <Link href="/app/chat" className="text-[var(--accent-primary)] hover:underline">
            Ask Denali
          </Link>{" "}
          or email support.
        </p>
      </div>
    </div>
  );
}
