"use client";

import { useState, FormEvent } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { LandingFooter } from "@/components/landing/LandingFooter";
import { ArrowRightIcon } from "@/components/icons";

const FAQ_SECTIONS = [
  {
    title: "Data Privacy & Security",
    items: [
      {
        q: "What data does Denali collect?",
        a: "We store only what's needed: your email (for login), conversation history, and appeal letters. If you connect Medicare via the official Medicare API, we also cache your claims and coverage data (encrypted, refreshed every 24 hours), along with basic demographics (age and gender only). We never store your full name, date of birth, address, Social Security Number, Medicare beneficiary ID, or bank details.",
      },
      {
        q: "Is my health data encrypted?",
        a: "Yes. All Medicare API tokens are encrypted with AES-256-GCM before storage. Data in transit uses TLS 1.2+. Your cached health data is only accessible to your authenticated account.",
      },
      {
        q: "Who can see my data?",
        a: "We share data only with the service providers needed to run the app: AWS (database, hosting, and AI via Bedrock), Stripe (payments), and Resend (email delivery — receives only your email address). We never share data for marketing or advertising. Each provider is contractually required to protect your data. See our Privacy Policy for details on what each provider receives and for how long.",
      },
      {
        q: "What happens if there's a data breach?",
        a: "We will notify affected users within 60 days via email, explaining what happened, what data was involved, and what steps to take. For breaches affecting 500 or more users, we also notify the FTC and HHS as required by law.",
      },
    ],
  },
  {
    title: "How We Use Your Health Data",
    items: [
      {
        q: "What happens when I connect Medicare?",
        a: "We use the official Medicare claims API to fetch your coverage status, recent claims, and any denied claims. This lets our AI personalize guidance — for example, referencing your actual coverage instead of asking you to look it up.",
      },
      {
        q: "Can I control how my health data is used?",
        a: "Yes. In Settings > Privacy & Data, you can toggle whether your health data is used in AI conversations, whether it's cached locally, and whether you share anonymous usage analytics.",
      },
    ],
  },
  {
    title: "Consent & Preferences",
    items: [
      {
        q: "What consents do I need to give?",
        a: "Using Denali for coverage guidance requires no consent or account. For appeals, we need your email. For health data features, we ask for explicit consent before accessing or using your Medicare records in conversations.",
      },
      {
        q: "Can I revoke consent?",
        a: "Anytime. Go to Settings > Privacy & Data and toggle off any consent. If you revoke health data consent, we stop using it in conversations immediately. You can also disconnect Medicare entirely.",
      },
    ],
  },
  {
    title: "Medicare Connection",
    items: [
      {
        q: "Is this connected to Medicare?",
        a: "We use the official Medicare claims API to access your claims and coverage data with your permission. We're working toward deeper Medicare integration as part of the CMS Health Technology Ecosystem.",
      },
    ],
  },
  {
    title: "Trial & Pricing",
    items: [
      {
        q: "Is Denali free?",
        a: "Every new account gets a 14-day free trial (3 messages/day, 1 appeal credit). After the trial, chat access is locked until you purchase a plan: Pay Per Appeal ($10/appeal, 5 messages/day) or Monthly ($20/month, 3 appeals + unlimited messages).",
      },
      {
        q: "Is there a free trial?",
        a: "Yes. Every new account gets a 14-day trial with 3 messages/day and 1 appeal credit. After the trial period, chat access is locked — choose Pay Per Appeal ($10/appeal) or Monthly ($20/month) to continue.",
      },
    ],
  },
  {
    title: "Appeal Letters",
    items: [
      {
        q: "How accurate are the appeal letters?",
        a: "Our letters cite real LCD/NCD policy numbers, use correct ICD-10 and CPT codes, and include relevant clinical evidence from PubMed. However, they should be reviewed by you and your healthcare provider before submission.",
      },
      {
        q: "Does Denali guarantee my appeal will be approved?",
        a: "No. We provide the strongest possible letter based on Medicare policy, but approval depends on your specific medical situation, documentation, and the reviewer. Our guidance helps maximize your chances.",
      },
    ],
  },
  {
    title: "AI Disclosure",
    items: [
      {
        q: "Is this AI-generated content?",
        a: "Yes. All responses are generated by AI (Claude via AWS Bedrock). Every message is clearly marked as AI-generated. Our guidance is based on real Medicare policies but does not replace clinical judgment.",
      },
      {
        q: "What are the limitations?",
        a: "Denali provides Medicare coverage guidance only — not medical advice, legal advice, or billing services. We support both Original Medicare and Medicare Advantage, though coverage rules differ between them. Always verify with your healthcare provider.",
      },
    ],
  },
  {
    title: "Account & Deletion",
    items: [
      {
        q: "Can I delete my account?",
        a: "Yes. Go to Settings > Danger Zone and request account deletion. We permanently delete your conversations, appeal letters, cached health data, Medicare connection, consent preferences, diabetes tracking data (logs, snapshots, and AI insights), and authentication credentials. Your Stripe subscription is cancelled. This action cannot be undone.",
      },
      {
        q: "What data is retained after deletion?",
        a: "Two categories survive deletion: (1) Anonymized, de-identified learning data (e.g., 'symptom X maps to code Y with Z% confidence') — no names, Medicare IDs, or account identifiers; and (2) Audit logs, which are retained for a minimum of 6 years as required by HIPAA. Audit logs record data access events (who accessed what, when, and why) and cannot be deleted on demand due to this regulatory obligation.",
      },
    ],
  },
  {
    title: "Accessibility",
    items: [
      {
        q: "Is Denali accessible?",
        a: "We follow WCAG guidelines: minimum 16px font size, adjustable text scaling, high contrast support, screen reader compatibility, and 44x44px minimum touch targets. Adjust text size in Settings > Accessibility.",
      },
    ],
  },
];

export default function FAQPage() {
  const router = useRouter();
  const [question, setQuestion] = useState("");
  const [expandedSections, setExpandedSections] = useState<Set<string>>(new Set());

  function toggleSection(title: string) {
    setExpandedSections((prev) => {
      const next = new Set(prev);
      if (next.has(title)) {
        next.delete(title);
      } else {
        next.add(title);
      }
      return next;
    });
  }

  function handleAsk(e: FormEvent) {
    e.preventDefault();
    const trimmed = question.trim();
    if (!trimmed) return;
    router.push(`/app/chat?message=${encodeURIComponent(trimmed)}`);
  }

  return (
    <>
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="font-[var(--font-serif)] text-3xl sm:text-4xl font-normal text-[var(--text-primary)] mb-2">
          Frequently Asked Questions
        </h1>
        <p className="text-[var(--text-secondary)] mb-2">
          How Denali handles your data, privacy, and Medicare guidance.
        </p>
        <p className="text-xs text-[var(--text-muted)] mb-8">
          Effective: March 5, 2026
        </p>

        {/* Ask bar */}
        <form onSubmit={handleAsk} className="mb-10">
          <div className="relative">
            <input
              type="text"
              value={question}
              onChange={(e) => setQuestion(e.target.value)}
              placeholder="Ask me anything about this website..."
              className="w-full px-5 py-4 pr-14 rounded-xl border border-[var(--border)] bg-[var(--bg-secondary)] text-[var(--text-primary)] text-base placeholder:text-[var(--text-muted)] focus:outline-none focus:border-[var(--accent-primary)] focus:ring-1 focus:ring-[var(--accent-primary)]/30 transition-colors"
            />
            <button
              type="submit"
              disabled={!question.trim()}
              className="absolute right-3 top-1/2 -translate-y-1/2 w-10 h-10 rounded-lg bg-[var(--accent-primary)] text-white flex items-center justify-center hover:opacity-90 transition-opacity disabled:opacity-40 disabled:cursor-not-allowed"
              aria-label="Ask Denali"
            >
              <ArrowRightIcon className="w-5 h-5" />
            </button>
          </div>
          <p className="text-xs text-[var(--text-muted)] mt-2">
            No signup required — get an instant answer from Denali.
          </p>
        </form>

        {/* Accordion sections */}
        <div className="space-y-2">
          {FAQ_SECTIONS.map((section) => {
            const isExpanded = expandedSections.has(section.title);
            return (
              <div
                key={section.title}
                className="rounded-xl border border-[var(--border)] bg-[var(--bg-secondary)] overflow-hidden"
              >
                <button
                  onClick={() => toggleSection(section.title)}
                  className="w-full flex items-center justify-between px-5 py-4 text-left hover:bg-[var(--bg-tertiary)] transition-colors"
                  aria-expanded={isExpanded}
                >
                  <span className="text-base font-semibold text-[var(--text-primary)]">
                    {section.title}
                  </span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-[var(--text-muted)]">
                      {section.items.length}
                    </span>
                    <ChevronIcon
                      className={`w-5 h-5 text-[var(--text-muted)] transition-transform duration-200 ${
                        isExpanded ? "rotate-180" : ""
                      }`}
                    />
                  </div>
                </button>

                {isExpanded && (
                  <div className="px-5 pb-5 space-y-5 border-t border-[var(--border)]">
                    {section.items.map((item) => (
                      <div key={item.q} className="pt-4">
                        <h3 className="text-sm font-medium text-[var(--text-primary)] mb-1.5">
                          {item.q}
                        </h3>
                        <p className="text-sm text-[var(--text-secondary)] leading-relaxed">
                          {item.a}
                        </p>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <p className="text-sm text-[var(--text-muted)] mt-10">
          Have more questions?{" "}
          <Link
            href="/app/chat"
            className="text-[var(--accent-primary)] hover:underline"
          >
            Ask Denali
          </Link>{" "}
          or email support.
        </p>
      </div>
      <LandingFooter />
    </>
  );
}

function ChevronIcon({ className }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth={2}
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 9l6 6 6-6" />
    </svg>
  );
}
