"use client";

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/Button";
import { AppealGate } from "./AppealGate";
import { MarkdownContent } from "@/components/chat/MarkdownContent";
import { BRAND } from "@/config";
import type { AppealLetterData } from "@/hooks/useChat";

interface AppealLetterModalProps {
  data: AppealLetterData;
  onClose: () => void;
  onReportOutcome?: () => void;
}

export function AppealLetterModal({
  data,
  onClose,
  onReportOutcome,
}: AppealLetterModalProps) {
  const [accessGranted, setAccessGranted] = useState(false);

  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(data.letterContent);
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement("textarea");
      textarea.value = data.letterContent;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
    }
  }, [data.letterContent]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([data.letterContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `appeal-letter-${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [data.letterContent]);

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleReportOutcome = useCallback(() => {
    onClose();
    onReportOutcome?.();
  }, [onClose, onReportOutcome]);

  // Format deadline for display
  const deadlineDisplay = data.appealDeadline
    ? new Date(data.appealDeadline).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white text-black max-w-2xl w-full max-h-[90vh] overflow-auto rounded-lg shadow-2xl">
        {/* Header - always visible */}
        <div className="no-print sticky top-0 bg-white border-b p-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Appeal Letter</h2>
          <div className="flex gap-2">
            {accessGranted && (
              <>
                <Button variant="secondary" size="sm" onClick={handleCopy}>
                  Copy
                </Button>
                <Button variant="secondary" size="sm" onClick={handleDownload}>
                  Download
                </Button>
                <Button variant="primary" size="sm" onClick={handlePrint}>
                  Print
                </Button>
              </>
            )}
            <Button variant="ghost" size="sm" onClick={onClose}>
              Close
            </Button>
          </div>
        </div>

        {/* Deadline banner */}
        {deadlineDisplay && (
          <div className="no-print bg-red-50 border-b border-red-200 px-4 py-3 text-red-800 text-sm font-medium">
            Appeal deadline: {deadlineDisplay} (120 days from denial date)
          </div>
        )}

        {/* Content wrapped in AppealGate */}
        <div className="p-8 print:p-4">
          <AppealGate onAccessGranted={() => setAccessGranted(true)}>
            <MarkdownContent content={data.letterContent} />
          </AppealGate>
        </div>

        {/* Footer - policy references + outcome link */}
        <div className="no-print border-t p-4">
          {data.policyReferences.length > 0 && (
            <p className="text-xs text-gray-500 mb-2">
              Policy references: {data.policyReferences.join(", ")}
            </p>
          )}
          <div className="flex items-center justify-between">
            <p className="text-xs text-gray-400">
              Generated by {BRAND.DOMAIN}
            </p>
            {accessGranted && onReportOutcome && (
              <button
                onClick={handleReportOutcome}
                className="text-xs text-blue-600 hover:text-blue-800 underline"
              >
                Report appeal outcome
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
