import Link from "next/link";
import { BRAND } from "@/config";
import { LandingFooter } from "@/components/landing";

const EFFECTIVE_DATE = "March 5, 2026";

const SECTIONS = [
  {
    id: "overview",
    title: "1. Overview",
    content: `${BRAND.NAME} ("we," "us," or "our") is a Medicare coverage guidance app run by ${BRAND.COMPANY_NAME}. This Privacy Policy explains how we collect, use, and protect your information when you use ${BRAND.DOMAIN} (the "Service"). By creating an account, you agree to this policy. You can review it before signing up. You can delete your account at any time if you no longer agree.`,
  },
  {
    id: "information-we-collect",
    title: "2. Information We Collect",
    subsections: [
      {
        title: "Information You Provide",
        items: [
          "Email address (for account creation and authentication via one-time passcodes)",
          "Phone number (for multi-factor authentication, if you choose to add it)",
          "Conversation content (your questions and our AI-generated responses about Medicare coverage)",
          "Appeal letter content (generated by our AI based on information you provide)",
          "Consent preferences (your choices about how your data is used)",
        ],
      },
      {
        title: "Medicare Health Data (With Your Explicit Consent)",
        items: [
          "Patient demographics (age and gender only — we do not store your full name, date of birth, address, or Medicare beneficiary ID)",
          "Coverage information (Medicare Part A/B enrollment, plan details)",
          "Claims and Explanation of Benefits (EOBs) including denied claims",
          "Conditions, medications, and screening history (extracted from your claims data)",
        ],
      },
      {
        title: "Information We Do NOT Collect",
        items: [
          "Full names, dates of birth, or mailing addresses",
          "Social Security Numbers (SSN)",
          "Medicare beneficiary IDs or insurance card numbers (we access data via secure OAuth, not card numbers)",
          "Bank account or financial information (payments processed by Stripe)",
          "Medical records beyond what Medicare provides",
        ],
      },
      {
        title: "Automatically Collected Information",
        items: [
          "Device type and browser information (for compatibility)",
          "IP address (for security and audit logging)",
          "Usage patterns (pages visited, features used — anonymized)",
        ],
      },
    ],
  },
  {
    id: "how-we-use",
    title: "3. How We Use Your Information",
    items: [
      "Provide personalized Medicare coverage guidance based on your situation",
      "Generate appeal letters when Medicare denies a claim",
      "Connect to the official Medicare claims API to access your Medicare data (only with your explicit consent)",
      "Personalize AI conversations with your health context (lab results, diagnoses, medications — only if you consent)",
      "Detect and alert you to potential claim denial risks before they happen",
      "Improve our service through anonymized, de-identified learning patterns",
      "Maintain audit logs for CMS compliance (who accessed what data, when, and why)",
      "Send you account-related communications (authentication codes, appeal status)",
    ],
  },
  {
    id: "medicare-data",
    title: "4. Medicare Health Data",
    paragraphs: [
      "We access your Medicare data through the official Medicare claims API. This connection uses OAuth 2.0 with PKCE (Proof Key for Code Exchange) for security — we never see or store your Medicare password.",
      "When you connect your Medicare account, you authorize CMS to share specific data with us. You can revoke this connection at any time in Settings.",
      "When you disconnect Medicare, we immediately and permanently delete all your cached health data. We do not keep, share, or use it after you disconnect. Data that was already anonymized for service improvement is not affected (see Section 7).",
    ],
    subsections: [
      {
        title: "How We Protect Your Medicare Data",
        items: [
          "OAuth tokens are encrypted at rest using AES-256-GCM encryption",
          "Health data is cached locally for up to 24 hours to reduce API calls, then refreshed",
          "All data access is logged in our audit system (who, what, when, why)",
          "Data in transit is protected by TLS 1.2+",
          "Application-level access controls ensure you can only access your own data through authenticated API routes",
        ],
      },
      {
        title: "Your Consent Controls",
        items: [
          "Health Data in AI: Choose whether your lab results, diagnoses, and medications are used to personalize AI conversations",
          "Health Data Storage: Choose whether your Medicare data is cached for faster access",
          "Analytics: Choose whether anonymized usage data helps us improve the service",
          "You can change these preferences anytime in Settings > Privacy & Data",
        ],
      },
    ],
  },
  {
    id: "data-sharing",
    title: "5. How We Share Your Information",
    paragraphs: [
      "We do not sell your personal information. We share data only in limited circumstances, described below with the scope and duration of each sharing relationship:",
    ],
    items: [
      "Stripe: Payment processing for subscriptions and per-appeal purchases. Sharing is transactional (one-time per payment event) — we never see or store your credit card number.",
      "CMS (Medicare API): We exchange data with the Medicare claims API only when you explicitly authorize the connection. Sharing is persistent while your connection is active and ceases immediately when you disconnect.",
      "AWS (Amazon Web Services): Our database (RDS PostgreSQL), application hosting (ECS/Fargate), AI processing (Bedrock), and email delivery (SES) provider. AWS is HIPAA-eligible and our Business Associate Agreement (BAA) was executed on February 25, 2026. Your account data, conversation history, and cached health data are stored in encrypted AWS RDS databases in us-east-1. Sharing is persistent for the lifetime of your account.",
      "Legal Requirements: We may disclose information if required by law, court order, or government regulation.",
      "Business Transfers: If our company is sold or merges with another, your data may be transferred. We will email you at least 30 days before the transfer happens. We will also notify CMS as soon as possible. Our access to Medicare data is tied to our specific company — if ownership changes, CMS must review and re-approve the new owner.",
      "Vendor Data Protection: Every company we work with must protect your data. They are required by contract to use safeguards that match the sensitivity of the data they handle. All providers handling health data are covered by Business Associate Agreements (BAAs). AWS is HIPAA-eligible and SOC 2 Type II certified. Our BAA with AWS (signed February 25, 2026) covers database (RDS), hosting (ECS/Fargate), AI processing (Bedrock), and email delivery (SES). Stripe is PCI DSS certified for payments.",
    ],
    subsections: [
      {
        title: "AWS Bedrock (Claude AI) Data Handling",
        items: [
          "Your conversation content (questions and context) is processed through Claude on AWS Bedrock to generate responses. Sharing is transactional (per-message) — each request is independent. Health data is only included if you have enabled the 'Health Data in AI' consent toggle.",
          "AWS Bedrock does not store or log your prompts and completions by default, and does not train models on your data.",
          "All data sent to AWS Bedrock is encrypted in transit via TLS 1.2+ and processed within HIPAA-eligible infrastructure covered by our AWS BAA executed February 25, 2026.",
          "AWS is SOC 2 Type II certified and HIPAA-eligible across all services we use (RDS, ECS/Fargate, Bedrock).",
        ],
      },
    ],
  },
  {
    id: "data-retention",
    title: "6. Data Retention",
    items: [
      "Account data: Retained until you delete your account",
      "Conversation history: Retained until you delete your account",
      "Appeal letters: Retained until you delete your account",
      "Cached health data: Refreshed every 24 hours; deleted when you disconnect Medicare or delete your account",
      "OAuth tokens: Encrypted; deleted when you disconnect Medicare or delete your account",
      "Audit logs: Retained for a minimum of 6 years per HIPAA requirements — this retention obligation applies even after account deletion and cannot be waived",
      "Anonymized learning data: Retained indefinitely (contains no personally identifiable information)",
      "Inactive accounts: Accounts with no sign-in activity for 24 months may receive a 30-day email notice before data is archived. You can reactivate by signing in during the notice period.",
    ],
  },
  {
    id: "account-deletion",
    title: "7. Account Deletion",
    paragraphs: [
      "You can delete your account at any time through Settings > Danger Zone. When you delete your account, we permanently and irreversibly delete:",
    ],
    items: [
      "Your Medicare connection and all cached health data",
      "All conversations and messages",
      "All appeal letters",
      "Your consent preferences",
      "Your diabetes tracking data (daily logs, lab snapshots, and AI-generated insights)",
      "Your authentication credentials",
      "Your Stripe subscription (if active)",
    ],
    afterItems:
      "After deletion, we keep only two things. First: anonymized learning data (for example, 'symptom X maps to code Y'). This data has no names, contact info, or Medicare IDs. We believe it cannot identify you. However, in rare cases, very specific medical patterns could theoretically help identify someone with an uncommon condition. We minimize this risk by aggregating the data. Second: audit logs are kept for at least 6 years as required by HIPAA. This applies even after you delete your account. Everything else listed above is permanently deleted. Note: Medicare claims may include information about family members, such as codes for hereditary conditions. We never share your health data with anyone — including relatives — without your permission.",
  },
  {
    id: "security",
    title: "8. Security Measures",
    items: [
      "AES-256-GCM encryption for OAuth tokens at rest",
      "TLS 1.2+ for all data in transit",
      "Application-level access controls — users can only access their own data through authenticated API routes",
      "Email-based one-time passcode (OTP) authentication",
      "Optional TOTP multi-factor authentication (authenticator app)",
      "PKCE (Proof Key for Code Exchange) for Medicare OAuth to prevent authorization code interception",
      "Comprehensive audit logging of all sensitive data access",
      "Automatic session management and token refresh",
    ],
  },
  {
    id: "hipaa",
    title: "9. HIPAA Compliance and Privacy Act",
    paragraphs: [
      "Your Medicare data is protected by federal law, including HIPAA and the Privacy Act of 1974. We follow all applicable federal and state laws for safeguarding this data. Our compliance measures include:",
    ],
    items: [
      "Technical safeguards: encryption, access controls, audit logging",
      "Administrative safeguards: workforce training, security policies, incident response procedures",
      "Physical safeguards: secure hosting through AWS (RDS, ECS/Fargate, Cognito) with SOC 2 and HIPAA-eligible services",
      "Every vendor that handles your health data must sign a Business Associate Agreement (BAA) with us. Our BAA with AWS (covering database, hosting, and AI services via Amazon RDS, ECS/Fargate, and Bedrock) was executed on February 25, 2026.",
    ],
    afterItems:
      "For detailed information about our HIPAA practices, see our HIPAA Compliance page.",
    afterLink: { href: "/hipaa", text: "View HIPAA Compliance" },
  },
  {
    id: "breach-notification",
    title: "10. Breach Notification",
    paragraphs: [
      "We follow federal breach notification rules, including the FTC Health Breach Notification Rule (16 CFR Part 318) and the HITECH Act. If your health data is exposed in a breach:",
    ],
    items: [
      "We will email you within 60 days. The notice will explain what happened, what data was involved, and what you can do",
      "The notice will describe the breach, the data involved, and the steps we took to fix it",
      "Steps you can take to protect yourself: check your Medicare Summary Notices for unfamiliar claims, call 1-800-MEDICARE (1-800-633-4227) if you suspect misuse, and review your credit report if personal info was involved",
      "For breaches affecting 500 or more individuals, we will also notify the FTC and HHS as required by law",
      "We have procedures in place to detect, investigate, and stop breaches quickly. See our HIPAA Compliance page for the full plan",
    ],
  },
  {
    id: "cms-framework",
    title: "11. CMS Interoperability Framework",
    paragraphs: [
      "We are part of the CMS Health Technology Ecosystem. Our app is listed under two categories: Conversational AI and Diabetes & Obesity Prevention. As part of this framework, we commit to:",
    ],
    items: [
      "Supporting patient identity verification through CMS-approved services (Medicare OAuth with IAL2/AAL2)",
      "Maintaining transparent audit logs of all data access",
      "Honoring patient consent preferences across all data operations",
      "Including request purpose codes on all health data queries",
      "Providing a 14-day free trial for Medicare beneficiaries",
      "Making our application available for CMS review and directory listing",
      "Clearly marking all AI-generated content and distinguishing it from clinical guidance",
      "Using 'Medicare' as the data source name in all user-facing communications, consistent with CMS guidance",
    ],
  },
  {
    id: "cookies",
    title: "12. Cookies & Local Storage",
    items: [
      "Authentication cookies: Secure, httpOnly session cookies for login state",
      "PKCE cookies: Temporary httpOnly cookies during Medicare OAuth (cleared after authorization)",
      "Theme preference: Stored in localStorage (dark/light/system)",
      "We do not use tracking cookies or third-party advertising cookies",
      "We do not participate in cross-site tracking or ad networks",
    ],
  },
  {
    id: "your-rights",
    title: "13. Your Rights",
    paragraphs: ["Depending on your jurisdiction, you may have the right to:"],
    items: [
      "Access: View all data we hold about you (conversation history, appeals, health data cache)",
      "Correction: Request correction of inaccurate data",
      "Deletion: Delete your account and all associated data (Settings > Danger Zone)",
      "Portability: Export your data in a readable format",
      "Consent Withdrawal: Revoke any consent at any time (Settings > Privacy & Data)",
      "Opt-Out: Disconnect your Medicare data connection at any time",
    ],
    afterItems:
      "California residents have additional rights under the CCPA/CPRA, including the right to know what personal information is collected and the right to opt-out of the sale of personal information. We do not sell personal information.",
  },
  {
    id: "children",
    title: "14. Children's Privacy",
    paragraphs: [
      "Our Service is designed for Medicare beneficiaries (generally age 65+) and their caregivers. We do not knowingly collect information from children under 13. If you believe we have inadvertently collected such information, please contact us and we will delete it promptly.",
    ],
  },
  {
    id: "changes",
    title: "15. Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. For material changes, we will notify registered users via email at least 30 days before the new policy takes effect, with a summary of what changed.",
      "If changes are due to new CMS rules, we will tell you what changed and how it affects your Medicare data.",
      "If you disagree with the changes, you may delete your account and all associated data before the effective date (Settings > Danger Zone). If you keep using the app after the new policy starts, you are agreeing to it.",
    ],
  },
  {
    id: "contact",
    title: "16. Contact Us",
    paragraphs: [
      "If you have questions about this Privacy Policy, your data, or your rights, you can:",
    ],
    items: [
      "Ask Denali directly in the chat for privacy-related questions",
      "Email us at admin@denali.health",
    ],
  },
];

interface Section {
  id: string;
  title: string;
  content?: string;
  paragraphs?: string[];
  items?: string[];
  afterItems?: string;
  afterLink?: { href: string; text: string };
  subsections?: {
    title: string;
    items: string[];
  }[];
}

function SectionBlock({ section }: { section: Section }) {
  return (
    <div id={section.id} className="mb-10">
      <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-4 pb-2 border-b border-[var(--border)]">
        {section.title}
      </h2>

      {section.content && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
          {section.content}
        </p>
      )}

      {section.paragraphs?.map((p, i) => (
        <p
          key={i}
          className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4"
        >
          {p}
        </p>
      ))}

      {section.items && (
        <ul className="list-disc list-outside pl-5 space-y-2 mb-4">
          {section.items.map((item, i) => (
            <li
              key={i}
              className="text-sm text-[var(--text-secondary)] leading-relaxed"
            >
              {item}
            </li>
          ))}
        </ul>
      )}

      {section.afterItems && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-2">
          {section.afterItems}
        </p>
      )}

      {section.afterLink && (
        <Link
          href={section.afterLink.href}
          className="text-sm text-[var(--accent-primary)] hover:underline"
        >
          {section.afterLink.text}
        </Link>
      )}

      {section.subsections?.map((sub, i) => (
        <div key={i} className="mt-4">
          <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
            {sub.title}
          </h3>
          <ul className="list-disc list-outside pl-5 space-y-2">
            {sub.items.map((item, j) => (
              <li
                key={j}
                className="text-sm text-[var(--text-secondary)] leading-relaxed"
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <>
      <div className="max-w-3xl mx-auto px-4 py-12">
        <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-2">
          Privacy Policy
        </h1>
        <p className="text-[var(--text-secondary)] mb-2">
          How {BRAND.NAME} collects, uses, and protects your information.
        </p>
        <p className="text-xs text-[var(--text-muted)] mb-10">
          Effective: {EFFECTIVE_DATE}
        </p>

        {/* Table of Contents */}
        <nav className="mb-10 p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)]">
          <h2 className="text-sm font-semibold text-[var(--text-primary)] mb-3">
            Contents
          </h2>
          <ol className="list-decimal list-inside space-y-1">
            {SECTIONS.map((section) => (
              <li key={section.id}>
                <a
                  href={`#${section.id}`}
                  className="text-sm text-[var(--accent-primary)] hover:underline"
                >
                  {section.title.replace(/^\d+\.\s/, "")}
                </a>
              </li>
            ))}
          </ol>
        </nav>

        {SECTIONS.map((section) => (
          <SectionBlock key={section.id} section={section} />
        ))}
      </div>
      <LandingFooter />
    </>
  );
}
