import Link from "next/link";
import { BRAND } from "@/config";

const EFFECTIVE_DATE = "February 8, 2026";

const SECTIONS = [
  {
    id: "overview",
    title: "1. Overview",
    content: `${BRAND.NAME} ("we," "us," or "our") is a Medicare claims intelligence application operated by ${BRAND.COMPANY_NAME}. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our website at ${BRAND.DOMAIN} and related services (collectively, the "Service"). By creating an account, you actively acknowledge and accept the practices described in this policy. You may review this policy before signing up, and you may delete your account at any time if you no longer agree.`,
  },
  {
    id: "information-we-collect",
    title: "2. Information We Collect",
    subsections: [
      {
        title: "Information You Provide",
        items: [
          "Email address (for account creation and authentication via one-time passcodes)",
          "Phone number (for multi-factor authentication, if you choose to add it)",
          "Conversation content (your questions and our AI-generated responses about Medicare coverage)",
          "Appeal letter content (generated by our AI based on information you provide)",
          "Consent preferences (your choices about how your data is used)",
        ],
      },
      {
        title: "Medicare Health Data (With Your Explicit Consent)",
        items: [
          "Patient demographics (name, date of birth, Medicare beneficiary ID — from your Medicare account)",
          "Coverage information (Medicare Part A/B enrollment, plan details)",
          "Claims and Explanation of Benefits (EOBs) including denied claims",
          "Conditions, medications, and screening history (extracted from your claims data)",
        ],
      },
      {
        title: "Information We Do NOT Collect",
        items: [
          "Full legal names or mailing addresses",
          "Social Security Numbers (SSN)",
          "Medicare insurance card numbers (we access data via secure OAuth, not card numbers)",
          "Bank account or financial information (payments processed by Stripe)",
          "Medical records beyond what Medicare provides",
        ],
      },
      {
        title: "Automatically Collected Information",
        items: [
          "Device type and browser information (for compatibility)",
          "IP address (for security and audit logging)",
          "Usage patterns (pages visited, features used — anonymized)",
        ],
      },
    ],
  },
  {
    id: "how-we-use",
    title: "3. How We Use Your Information",
    items: [
      "Provide personalized Medicare coverage guidance based on your situation",
      "Generate appeal letters when Medicare denies a claim",
      "Connect to the official Medicare claims API to access your Medicare data (only with your explicit consent)",
      "Personalize AI conversations with your health context (lab results, diagnoses, medications — only if you consent)",
      "Detect and alert you to potential claim denial risks before they happen",
      "Improve our service through anonymized, de-identified learning patterns",
      "Maintain audit logs for CMS compliance (who accessed what data, when, and why)",
      "Send you account-related communications (authentication codes, appeal status)",
    ],
  },
  {
    id: "medicare-data",
    title: "4. Medicare Health Data",
    paragraphs: [
      "We access your Medicare data through the official Medicare claims API. This connection uses OAuth 2.0 with PKCE (Proof Key for Code Exchange) for security — we never see or store your Medicare password.",
      "When you connect your Medicare account, you authorize CMS to share specific data with us. You can revoke this connection at any time in Settings.",
    ],
    subsections: [
      {
        title: "How We Protect Your Medicare Data",
        items: [
          "OAuth tokens are encrypted at rest using AES-256-GCM encryption",
          "Health data is cached locally for up to 24 hours to reduce API calls, then refreshed",
          "All data access is logged in our audit system (who, what, when, why)",
          "Data in transit is protected by TLS 1.2+",
          "Row-Level Security (RLS) ensures you can only access your own data",
        ],
      },
      {
        title: "Your Consent Controls",
        items: [
          "Health Data in AI: Choose whether your lab results, diagnoses, and medications are used to personalize AI conversations",
          "Health Data Storage: Choose whether your Medicare data is cached for faster access",
          "Analytics: Choose whether anonymized usage data helps us improve the service",
          "You can change these preferences anytime in Settings > Privacy & Data",
        ],
      },
    ],
  },
  {
    id: "data-sharing",
    title: "5. How We Share Your Information",
    paragraphs: [
      "We do not sell your personal information. We share data only in limited circumstances, described below with the scope and duration of each sharing relationship:",
    ],
    items: [
      "Stripe: Payment processing for subscriptions and per-appeal purchases. Sharing is transactional (one-time per payment event) — we never see or store your credit card number.",
      "CMS (Medicare API): We exchange data with the Medicare claims API only when you explicitly authorize the connection. Sharing is persistent while your connection is active and ceases immediately when you disconnect.",
      "Supabase: Our database provider hosts your account data, conversation history, and cached health data with encryption at rest. Sharing is persistent for the lifetime of your account.",
      "Vercel: Our hosting provider processes web requests. Sharing is transactional (per-request) — server-side logs are retained for up to 30 days.",
      "Legal Requirements: We may disclose information if required by law, court order, or government regulation.",
      "Business Transfers: In the event of a merger, acquisition, or sale of assets, your personal information may be transferred. We will notify you via email at least 30 days before your data is transferred and becomes subject to a different privacy policy.",
    ],
    subsections: [
      {
        title: "Anthropic (Claude AI) Data Handling",
        items: [
          "Your conversation content (questions and context) is sent to Anthropic's Claude API to generate responses. Sharing is transactional (per-message) — each request is independent. Health data is only included if you have enabled the 'Health Data in AI' consent toggle.",
          "Anthropic does not train its models on data submitted through the API. Your conversations are not used to improve Claude or any other Anthropic product.",
          "Anthropic may retain API inputs and outputs for up to 30 days for safety and abuse monitoring purposes, after which they are automatically deleted.",
          "All data sent to Anthropic is encrypted in transit via TLS 1.2+. Anthropic is SOC 2 Type II certified.",
          "For full details, see Anthropic's API Data Usage Policy at anthropic.com/policies.",
        ],
      },
    ],
  },
  {
    id: "data-retention",
    title: "6. Data Retention",
    items: [
      "Account data: Retained until you delete your account",
      "Conversation history: Retained until you delete your account",
      "Appeal letters: Retained until you delete your account",
      "Cached health data: Refreshed every 24 hours; deleted when you disconnect Medicare or delete your account",
      "OAuth tokens: Encrypted; deleted when you disconnect Medicare or delete your account",
      "Audit logs: Retained for compliance purposes (minimum 6 years per HIPAA requirements)",
      "Anonymized learning data: Retained indefinitely (contains no personally identifiable information)",
      "Inactive accounts: Accounts with no sign-in activity for 24 months will receive a 30-day email notice before data is archived. You can reactivate by signing in during the notice period.",
    ],
  },
  {
    id: "account-deletion",
    title: "7. Account Deletion",
    paragraphs: [
      "You can delete your account at any time through Settings > Danger Zone. When you delete your account, we permanently and irreversibly delete:",
    ],
    items: [
      "Your Medicare connection and all cached health data",
      "All conversations and messages",
      "All appeal letters",
      "Your consent preferences",
      "Your authentication credentials",
      "Your Stripe subscription (if active)",
      "All audit log entries linked to your account",
    ],
    afterItems:
      "The only data retained after deletion is anonymized, de-identified learning data (e.g., 'symptom phrase X maps to diagnosis code Y with Z% confidence'). This data cannot be traced back to any individual.",
  },
  {
    id: "security",
    title: "8. Security Measures",
    items: [
      "AES-256-GCM encryption for OAuth tokens at rest",
      "TLS 1.2+ for all data in transit",
      "Row-Level Security (RLS) in our database — users can only access their own data",
      "Email-based one-time passcode (OTP) authentication",
      "Optional TOTP multi-factor authentication (authenticator app)",
      "PKCE (Proof Key for Code Exchange) for Medicare OAuth to prevent authorization code interception",
      "Comprehensive audit logging of all sensitive data access",
      "Automatic session management and token refresh",
    ],
  },
  {
    id: "hipaa",
    title: "9. HIPAA Compliance",
    paragraphs: [
      "We are committed to protecting your health information in accordance with the Health Insurance Portability and Accountability Act (HIPAA). Our compliance measures include:",
    ],
    items: [
      "Technical safeguards: encryption, access controls, audit logging",
      "Administrative safeguards: workforce training, security policies, incident response procedures",
      "Physical safeguards: secure hosting through SOC 2 compliant providers (Supabase, Vercel)",
      "Business Associate Agreements (BAAs) are maintained with all service providers who access, process, or store protected health information on our behalf",
    ],
    afterItems:
      "For detailed information about our HIPAA practices, see our HIPAA Compliance page.",
    afterLink: { href: "/hipaa", text: "View HIPAA Compliance" },
  },
  {
    id: "breach-notification",
    title: "10. Breach Notification",
    paragraphs: [
      "As a personal health record vendor, we comply with the FTC Health Breach Notification Rule (16 CFR Part 318) and the HITECH Act breach notification requirements. In the event of a breach of unsecured health data:",
    ],
    items: [
      "We will notify affected individuals within 60 days of discovery via email, explaining what happened, what data was involved, and what steps to take",
      "Notification will include a description of the breach, the types of data involved, steps we have taken to investigate and mitigate, and recommended actions for affected users",
      "For breaches affecting 500 or more individuals, we will also notify the FTC and HHS as required by law",
      "We maintain incident response procedures to detect, investigate, and contain potential breaches promptly (see our HIPAA Compliance page for the full Incident Response Plan)",
    ],
  },
  {
    id: "cms-framework",
    title: "11. CMS Interoperability Framework",
    paragraphs: [
      "We participate in the CMS Health Technology Ecosystem as a Patient-Facing App under two categories: Conversational AI Assistants and Diabetes & Obesity Prevention. As part of this framework, we commit to:",
    ],
    items: [
      "Supporting patient identity verification through CMS-approved services (Medicare OAuth with IAL2/AAL2)",
      "Maintaining transparent audit logs of all data access",
      "Honoring patient consent preferences across all data operations",
      "Including request purpose codes on all health data queries",
      "Providing a 14-day free trial for Medicare beneficiaries",
      "Making our application available for CMS review and directory listing",
      "Clearly marking all AI-generated content and distinguishing it from clinical guidance",
      "Publishing a Model Privacy Notice (ONC format) for plain-language data handling transparency",
    ],
    afterLink: { href: "/privacy-notice", text: "View Model Privacy Notice" },
  },
  {
    id: "cookies",
    title: "12. Cookies & Local Storage",
    items: [
      "Authentication cookies: Secure, httpOnly session cookies for login state",
      "PKCE cookies: Temporary httpOnly cookies during Medicare OAuth (cleared after authorization)",
      "Theme preference: Stored in localStorage (dark/light/system)",
      "We do not use tracking cookies or third-party advertising cookies",
      "We do not participate in cross-site tracking or ad networks",
    ],
  },
  {
    id: "your-rights",
    title: "13. Your Rights",
    paragraphs: ["Depending on your jurisdiction, you may have the right to:"],
    items: [
      "Access: View all data we hold about you (conversation history, appeals, health data cache)",
      "Correction: Request correction of inaccurate data",
      "Deletion: Delete your account and all associated data (Settings > Danger Zone)",
      "Portability: Export your data in a readable format",
      "Consent Withdrawal: Revoke any consent at any time (Settings > Privacy & Data)",
      "Opt-Out: Disconnect your Medicare data connection at any time",
    ],
    afterItems:
      "California residents have additional rights under the CCPA/CPRA, including the right to know what personal information is collected and the right to opt-out of the sale of personal information. We do not sell personal information.",
  },
  {
    id: "children",
    title: "14. Children's Privacy",
    paragraphs: [
      "Our Service is designed for Medicare beneficiaries (generally age 65+) and their caregivers. We do not knowingly collect information from children under 13. If you believe we have inadvertently collected such information, please contact us and we will delete it promptly.",
    ],
  },
  {
    id: "changes",
    title: "15. Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. For material changes, we will notify registered users via email at least 30 days before the new policy takes effect, with a summary of what changed.",
      "If changes are driven by CMS regulatory updates or modifications to the CMS Interoperability Framework, we will specifically identify those changes and explain how they affect your Medicare data handling.",
      "If you disagree with the changes, you may delete your account and all associated data before the effective date (Settings > Danger Zone). Continued use of the Service after the effective date constitutes acceptance of the updated policy.",
    ],
  },
  {
    id: "contact",
    title: "16. Contact Us",
    paragraphs: [
      "If you have questions about this Privacy Policy, your data, or your rights, you can:",
    ],
    items: [
      "Ask Denali directly in the chat for privacy-related questions",
      "Email us at admin@denali.health",
      `Write to: ${BRAND.COMPANY_NAME}, Privacy Inquiries`,
      "Review our Model Privacy Notice for a plain-language summary of our data practices",
    ],
    afterLink: { href: "/privacy-notice", text: "View Model Privacy Notice" },
  },
];

interface Section {
  id: string;
  title: string;
  content?: string;
  paragraphs?: string[];
  items?: string[];
  afterItems?: string;
  afterLink?: { href: string; text: string };
  subsections?: {
    title: string;
    items: string[];
  }[];
}

function SectionBlock({ section }: { section: Section }) {
  return (
    <div id={section.id} className="mb-10">
      <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-4 pb-2 border-b border-[var(--border)]">
        {section.title}
      </h2>

      {section.content && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
          {section.content}
        </p>
      )}

      {section.paragraphs?.map((p, i) => (
        <p
          key={i}
          className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4"
        >
          {p}
        </p>
      ))}

      {section.items && (
        <ul className="list-disc list-outside pl-5 space-y-2 mb-4">
          {section.items.map((item, i) => (
            <li
              key={i}
              className="text-sm text-[var(--text-secondary)] leading-relaxed"
            >
              {item}
            </li>
          ))}
        </ul>
      )}

      {section.afterItems && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-2">
          {section.afterItems}
        </p>
      )}

      {section.afterLink && (
        <Link
          href={section.afterLink.href}
          className="text-sm text-[var(--accent-primary)] hover:underline"
        >
          {section.afterLink.text}
        </Link>
      )}

      {section.subsections?.map((sub, i) => (
        <div key={i} className="mt-4">
          <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
            {sub.title}
          </h3>
          <ul className="list-disc list-outside pl-5 space-y-2">
            {sub.items.map((item, j) => (
              <li
                key={j}
                className="text-sm text-[var(--text-secondary)] leading-relaxed"
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-2">
        Privacy Policy
      </h1>
      <p className="text-[var(--text-secondary)] mb-2">
        How {BRAND.NAME} collects, uses, and protects your information.
      </p>
      <p className="text-xs text-[var(--text-muted)] mb-10">
        Effective: {EFFECTIVE_DATE}
      </p>

      {/* Table of Contents */}
      <nav className="mb-10 p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)]">
        <h2 className="text-sm font-semibold text-[var(--text-primary)] mb-3">
          Contents
        </h2>
        <ol className="list-decimal list-inside space-y-1">
          {SECTIONS.map((section) => (
            <li key={section.id}>
              <a
                href={`#${section.id}`}
                className="text-sm text-[var(--accent-primary)] hover:underline"
              >
                {section.title.replace(/^\d+\.\s/, "")}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {SECTIONS.map((section) => (
        <SectionBlock key={section.id} section={section} />
      ))}

      <div className="border-t border-[var(--border)] pt-6 mt-10">
        <p className="text-xs text-[var(--text-muted)]">
          {BRAND.NAME} is {BRAND.COMPANY_ATTRIBUTION}.{" "}
          {BRAND.COPYRIGHT_TEXT}
        </p>
      </div>
    </div>
  );
}
