import Link from "next/link";
import { BRAND } from "@/config";

const EFFECTIVE_DATE = "February 8, 2026";

const SECTIONS = [
  {
    id: "overview",
    title: "1. Overview",
    content: `${BRAND.NAME} ("we," "us," or "our") is a Medicare claims intelligence application operated by ${BRAND.COMPANY_NAME}. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our website at ${BRAND.DOMAIN} and related services (collectively, the "Service"). By using the Service, you agree to the practices described in this policy.`,
  },
  {
    id: "information-we-collect",
    title: "2. Information We Collect",
    subsections: [
      {
        title: "Information You Provide",
        items: [
          "Email address (for account creation and authentication via one-time passcodes)",
          "Phone number (for multi-factor authentication, if you choose to add it)",
          "Conversation content (your questions and our AI-generated responses about Medicare coverage)",
          "Appeal letter content (generated by our AI based on information you provide)",
          "Consent preferences (your choices about how your data is used)",
        ],
      },
      {
        title: "Medicare Health Data (With Your Explicit Consent)",
        items: [
          "Patient demographics (name, date of birth, Medicare beneficiary ID — from CMS Blue Button 2.0)",
          "Coverage information (Medicare Part A/B enrollment, plan details)",
          "Claims and Explanation of Benefits (EOBs) including denied claims",
          "Lab results (A1C, glucose, BMI, blood pressure — from FHIR Observations)",
          "Diagnoses (conditions from FHIR Condition resources)",
          "Medications (prescriptions from FHIR MedicationRequest resources)",
        ],
      },
      {
        title: "Information We Do NOT Collect",
        items: [
          "Full legal names or mailing addresses",
          "Social Security Numbers (SSN)",
          "Medicare insurance card numbers (we access data via secure OAuth, not card numbers)",
          "Bank account or financial information (payments processed by Stripe)",
          "Medical records beyond what CMS Blue Button provides",
        ],
      },
      {
        title: "Automatically Collected Information",
        items: [
          "Device type and browser information (for compatibility)",
          "IP address (for security and audit logging)",
          "Usage patterns (pages visited, features used — anonymized)",
        ],
      },
    ],
  },
  {
    id: "how-we-use",
    title: "3. How We Use Your Information",
    items: [
      "Provide personalized Medicare coverage guidance based on your situation",
      "Generate appeal letters when Medicare denies a claim",
      "Connect to CMS Blue Button 2.0 to access your Medicare data (only with your explicit consent)",
      "Personalize AI conversations with your health context (lab results, diagnoses, medications — only if you consent)",
      "Detect and alert you to potential claim denial risks before they happen",
      "Improve our service through anonymized, de-identified learning patterns",
      "Maintain audit logs for CMS compliance (who accessed what data, when, and why)",
      "Send you account-related communications (authentication codes, appeal status)",
    ],
  },
  {
    id: "medicare-data",
    title: "4. Medicare Health Data (Blue Button 2.0)",
    paragraphs: [
      "We access your Medicare data through CMS Blue Button 2.0, the official Medicare API. This connection uses OAuth 2.0 with PKCE (Proof Key for Code Exchange) for security — we never see or store your Medicare.gov password.",
      "When you connect your Medicare account, you authorize CMS to share specific data with us. You can revoke this connection at any time in Settings.",
    ],
    subsections: [
      {
        title: "How We Protect Your Medicare Data",
        items: [
          "OAuth tokens are encrypted at rest using AES-256-GCM encryption",
          "Health data is cached locally for up to 24 hours to reduce API calls, then refreshed",
          "All data access is logged in our audit system (who, what, when, why)",
          "Data in transit is protected by TLS 1.2+",
          "Row-Level Security (RLS) ensures you can only access your own data",
        ],
      },
      {
        title: "Your Consent Controls",
        items: [
          "Health Data in AI: Choose whether your lab results, diagnoses, and medications are used to personalize AI conversations",
          "Health Data Storage: Choose whether your Medicare data is cached for faster access",
          "Analytics: Choose whether anonymized usage data helps us improve the service",
          "You can change these preferences anytime in Settings > Privacy & Data",
        ],
      },
    ],
  },
  {
    id: "data-sharing",
    title: "5. How We Share Your Information",
    paragraphs: [
      "We do not sell your personal information. We share data only in limited circumstances:",
    ],
    items: [
      "Anthropic (Claude AI): Your conversation content is sent to Anthropic's API to generate responses. Anthropic's usage policies apply to this processing. We do not send your health data to Anthropic unless you have enabled the 'Health Data in AI' consent toggle.",
      "Stripe: Payment processing for subscriptions and per-appeal purchases. We never see or store your credit card number — Stripe handles this directly.",
      "CMS (Blue Button): We exchange data with CMS Blue Button 2.0 only when you explicitly authorize the connection.",
      "Supabase: Our database provider hosts your account data, conversation history, and cached health data with encryption at rest.",
      "Vercel: Our hosting provider processes web requests. Server-side logs may contain request metadata.",
      "Legal Requirements: We may disclose information if required by law, court order, or government regulation.",
    ],
  },
  {
    id: "data-retention",
    title: "6. Data Retention",
    items: [
      "Account data: Retained until you delete your account",
      "Conversation history: Retained until you delete your account",
      "Appeal letters: Retained until you delete your account",
      "Cached health data: Refreshed every 24 hours; deleted when you disconnect Medicare or delete your account",
      "OAuth tokens: Encrypted; deleted when you disconnect Medicare or delete your account",
      "Audit logs: Retained for compliance purposes (minimum 6 years per HIPAA requirements)",
      "Anonymized learning data: Retained indefinitely (contains no personally identifiable information)",
    ],
  },
  {
    id: "account-deletion",
    title: "7. Account Deletion",
    paragraphs: [
      "You can delete your account at any time through Settings > Danger Zone. When you delete your account, we permanently and irreversibly delete:",
    ],
    items: [
      "Your Blue Button connection and all cached health data",
      "All conversations and messages",
      "All appeal letters",
      "Your consent preferences",
      "Your authentication credentials",
      "Your Stripe subscription (if active)",
      "All audit log entries linked to your account",
    ],
    afterItems:
      "The only data retained after deletion is anonymized, de-identified learning data (e.g., 'symptom phrase X maps to diagnosis code Y with Z% confidence'). This data cannot be traced back to any individual.",
  },
  {
    id: "security",
    title: "8. Security Measures",
    items: [
      "AES-256-GCM encryption for OAuth tokens at rest",
      "TLS 1.2+ for all data in transit",
      "Row-Level Security (RLS) in our database — users can only access their own data",
      "Email-based one-time passcode (OTP) authentication",
      "Optional TOTP multi-factor authentication (authenticator app)",
      "PKCE (Proof Key for Code Exchange) for Blue Button OAuth to prevent authorization code interception",
      "Comprehensive audit logging of all sensitive data access",
      "Automatic session management and token refresh",
    ],
  },
  {
    id: "hipaa",
    title: "9. HIPAA Compliance",
    paragraphs: [
      "We are committed to protecting your health information in accordance with the Health Insurance Portability and Accountability Act (HIPAA). Our compliance measures include:",
    ],
    items: [
      "Technical safeguards: encryption, access controls, audit logging",
      "Administrative safeguards: workforce training, security policies, incident response procedures",
      "Physical safeguards: secure hosting through SOC 2 compliant providers (Supabase, Vercel)",
      "Business Associate Agreements (BAAs) with service providers who access protected health information",
    ],
    afterItems:
      "For detailed information about our HIPAA practices, see our HIPAA Compliance page.",
    afterLink: { href: "/hipaa", text: "View HIPAA Compliance" },
  },
  {
    id: "cms-framework",
    title: "10. CMS Interoperability Framework",
    paragraphs: [
      "We participate in the CMS Health Technology Ecosystem as a Patient-Facing App under two categories: Conversational AI Assistants and Diabetes & Obesity Prevention. As part of this framework, we commit to:",
    ],
    items: [
      "Supporting patient identity verification through CMS-approved services (Blue Button OAuth with IAL2/AAL2 via Medicare.gov)",
      "Maintaining transparent audit logs of all data access",
      "Honoring patient consent preferences across all data operations",
      "Including request purpose codes on all health data queries",
      "Providing a 30-day free trial for Medicare beneficiaries",
      "Making our application available for CMS review and directory listing",
      "Clearly marking all AI-generated content and distinguishing it from clinical guidance",
    ],
  },
  {
    id: "cookies",
    title: "11. Cookies & Local Storage",
    items: [
      "Authentication cookies: Secure, httpOnly session cookies for login state",
      "PKCE cookies: Temporary httpOnly cookies during Blue Button OAuth (cleared after authorization)",
      "Theme preference: Stored in localStorage (dark/light/system)",
      "We do not use tracking cookies or third-party advertising cookies",
      "We do not participate in cross-site tracking or ad networks",
    ],
  },
  {
    id: "your-rights",
    title: "12. Your Rights",
    paragraphs: ["Depending on your jurisdiction, you may have the right to:"],
    items: [
      "Access: View all data we hold about you (conversation history, appeals, health data cache)",
      "Correction: Request correction of inaccurate data",
      "Deletion: Delete your account and all associated data (Settings > Danger Zone)",
      "Portability: Export your data in a readable format",
      "Consent Withdrawal: Revoke any consent at any time (Settings > Privacy & Data)",
      "Opt-Out: Disconnect your Medicare data connection at any time",
    ],
    afterItems:
      "California residents have additional rights under the CCPA/CPRA, including the right to know what personal information is collected and the right to opt-out of the sale of personal information. We do not sell personal information.",
  },
  {
    id: "children",
    title: "13. Children's Privacy",
    paragraphs: [
      "Our Service is designed for Medicare beneficiaries (generally age 65+) and their caregivers. We do not knowingly collect information from children under 13. If you believe we have inadvertently collected such information, please contact us and we will delete it promptly.",
    ],
  },
  {
    id: "changes",
    title: "14. Changes to This Policy",
    paragraphs: [
      "We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy with a new effective date. Your continued use of the Service after changes constitutes acceptance of the updated policy.",
    ],
  },
  {
    id: "contact",
    title: "15. Contact Us",
    paragraphs: [
      "If you have questions about this Privacy Policy, your data, or your rights, you can:",
    ],
    items: [
      "Ask Denali directly in the chat for privacy-related questions",
      `Email us at privacy@${BRAND.DOMAIN.replace("www.", "")}`,
      `Write to: ${BRAND.COMPANY_NAME}, Privacy Inquiries`,
    ],
  },
];

interface Section {
  id: string;
  title: string;
  content?: string;
  paragraphs?: string[];
  items?: string[];
  afterItems?: string;
  afterLink?: { href: string; text: string };
  subsections?: {
    title: string;
    items: string[];
  }[];
}

function SectionBlock({ section }: { section: Section }) {
  return (
    <div id={section.id} className="mb-10">
      <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-4 pb-2 border-b border-[var(--border)]">
        {section.title}
      </h2>

      {section.content && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
          {section.content}
        </p>
      )}

      {section.paragraphs?.map((p, i) => (
        <p
          key={i}
          className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4"
        >
          {p}
        </p>
      ))}

      {section.items && (
        <ul className="list-disc list-outside pl-5 space-y-2 mb-4">
          {section.items.map((item, i) => (
            <li
              key={i}
              className="text-sm text-[var(--text-secondary)] leading-relaxed"
            >
              {item}
            </li>
          ))}
        </ul>
      )}

      {section.afterItems && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-2">
          {section.afterItems}
        </p>
      )}

      {section.afterLink && (
        <Link
          href={section.afterLink.href}
          className="text-sm text-[var(--accent-primary)] hover:underline"
        >
          {section.afterLink.text}
        </Link>
      )}

      {section.subsections?.map((sub, i) => (
        <div key={i} className="mt-4">
          <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
            {sub.title}
          </h3>
          <ul className="list-disc list-outside pl-5 space-y-2">
            {sub.items.map((item, j) => (
              <li
                key={j}
                className="text-sm text-[var(--text-secondary)] leading-relaxed"
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

export default function PrivacyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-2">
        Privacy Policy
      </h1>
      <p className="text-[var(--text-secondary)] mb-2">
        How {BRAND.NAME} collects, uses, and protects your information.
      </p>
      <p className="text-xs text-[var(--text-muted)] mb-10">
        Effective: {EFFECTIVE_DATE}
      </p>

      {/* Table of Contents */}
      <nav className="mb-10 p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)]">
        <h2 className="text-sm font-semibold text-[var(--text-primary)] mb-3">
          Contents
        </h2>
        <ol className="list-decimal list-inside space-y-1">
          {SECTIONS.map((section) => (
            <li key={section.id}>
              <a
                href={`#${section.id}`}
                className="text-sm text-[var(--accent-primary)] hover:underline"
              >
                {section.title.replace(/^\d+\.\s/, "")}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {SECTIONS.map((section) => (
        <SectionBlock key={section.id} section={section} />
      ))}

      <div className="border-t border-[var(--border)] pt-6 mt-10">
        <p className="text-xs text-[var(--text-muted)]">
          {BRAND.NAME} is {BRAND.COMPANY_ATTRIBUTION}.{" "}
          {BRAND.COPYRIGHT_TEXT}
        </p>
      </div>
    </div>
  );
}
