"use client";

import { useCallback, useRef } from "react";
import { Button } from "@/components/ui/Button";

export interface ChecklistData {
  patientName?: string;
  serviceName: string;
  providerName?: string;
  generatedDate: string;
  requirements: string[];
  questions: string[];
  notes?: string;
}

interface PrintableChecklistProps {
  data: ChecklistData;
  onClose?: () => void;
  onPrint?: () => void;
  onEmail?: () => void;
}

/**
 * Printable checklist view based on guidance-generation SKILL.md format
 */
export function PrintableChecklist({
  data,
  onClose,
  onPrint,
  onEmail,
}: PrintableChecklistProps) {
  const checklistRef = useRef<HTMLDivElement>(null);

  const handlePrint = useCallback(() => {
    window.print();
    onPrint?.();
  }, [onPrint]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4">
      <div className="bg-white text-black max-w-2xl w-full max-h-[90vh] overflow-auto rounded-lg shadow-2xl">
        {/* Header - hidden in print */}
        <div className="no-print sticky top-0 bg-white border-b p-4 flex items-center justify-between">
          <h2 className="text-lg font-semibold">Print Preview</h2>
          <div className="flex gap-2">
            {onEmail && (
              <Button variant="secondary" onClick={onEmail}>
                Email
              </Button>
            )}
            <Button variant="primary" onClick={handlePrint}>
              Print
            </Button>
            {onClose && (
              <Button variant="ghost" onClick={onClose}>
                Close
              </Button>
            )}
          </div>
        </div>

        {/* Printable Content */}
        <div ref={checklistRef} className="p-8 print:p-4">
          {/* Document Header */}
          <div className="border-2 border-black mb-6">
            <div className="bg-blue-600 text-white text-center py-3 font-bold text-lg">
              MEDICARE COVERAGE CHECKLIST
            </div>
            <div className="text-center text-sm py-1 border-t border-black">
              Generated by denali.health | {data.generatedDate}
            </div>
          </div>

          {/* Patient Info */}
          <div className="grid grid-cols-3 gap-4 mb-6 text-sm">
            <div>
              <span className="font-semibold">PATIENT:</span>{" "}
              {data.patientName || "________________"}
            </div>
            <div>
              <span className="font-semibold">SERVICE:</span> {data.serviceName}
            </div>
            <div>
              <span className="font-semibold">DOCTOR:</span>{" "}
              {data.providerName || "________________"}
            </div>
          </div>

          {/* Requirements Section */}
          <div className="mb-6">
            <div className="bg-gray-100 border border-black px-3 py-2 font-bold mb-2">
              WHAT MEDICARE NEEDS DOCUMENTED:
            </div>
            <div className="border border-black p-4">
              <ul className="space-y-3">
                {data.requirements.map((req, index) => (
                  <li key={index} className="flex items-start gap-3">
                    <span className="inline-block w-5 h-5 border-2 border-black flex-shrink-0 mt-0.5" />
                    <span>{req}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Questions Section */}
          <div className="mb-6">
            <div className="bg-gray-100 border border-black px-3 py-2 font-bold mb-2">
              QUESTIONS TO ASK YOUR DOCTOR:
            </div>
            <div className="border border-black p-4">
              <ul className="space-y-2">
                {data.questions.map((q, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-blue-600">•</span>
                    <span>{q}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Notes Section */}
          <div className="mb-6">
            <div className="bg-gray-100 border border-black px-3 py-2 font-bold mb-2">
              NOTES:
            </div>
            <div className="border border-black p-4 min-h-[100px]">
              {data.notes || (
                <span className="text-gray-400 italic">
                  Space for your notes...
                </span>
              )}
            </div>
          </div>

          {/* Footer */}
          <div className="border-t-2 border-black pt-4 text-xs text-gray-600 text-center">
            <p>
              This guidance is based on Medicare policies as of {data.generatedDate}.
            </p>
            <p>Your doctor makes the final decisions about your care.</p>
            <p className="mt-2">Questions? Visit denali.health</p>
          </div>
        </div>
      </div>
    </div>
  );
}
