import Link from "next/link";
import { BRAND } from "@/config";
import { LandingFooter } from "@/components/landing";

const EFFECTIVE_DATE = "March 5, 2026";

const SECTIONS = [
  {
    id: "service-description",
    title: "1. Service Description",
    paragraphs: [
      `${BRAND.NAME} is a Medicare claims intelligence application that provides AI-powered coverage guidance, appeal letter generation, diabetes management coaching, and weight management guidance. The Service uses artificial intelligence (Claude via AWS Bedrock) to help you understand Medicare coverage rules, identify potential denial risks, and generate appeal letters when claims are denied.`,
      `The Service is coverage guidance only — not medical advice, legal advice, or billing services. All AI-generated content is clearly marked and should not be used as a substitute for professional medical or legal counsel.`,
    ],
  },
  {
    id: "acceptance",
    title: "2. Acceptance of Terms",
    paragraphs: [
      "By creating an account, you actively acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy. Account creation requires an affirmative action (entering your email and verifying a one-time passcode) — we do not assume acceptance through passive use.",
      "If you do not agree with any part of these Terms, do not create an account. If you have already created an account and no longer agree, you may delete your account at any time through Settings > Danger Zone.",
    ],
  },
  {
    id: "eligibility",
    title: "3. Eligibility",
    paragraphs: [
      "The Service is designed for Medicare beneficiaries — both Original Medicare and Medicare Advantage — (generally age 65 and older) and their authorized caregivers. You must be at least 18 years of age to create an account. By using the Service, you represent that you meet these eligibility requirements.",
    ],
  },
  {
    id: "account-terms",
    title: "4. Account Terms",
    items: [
      "Account creation requires a valid email address, verified via one-time passcode (OTP)",
      "You may optionally enable TOTP-based multi-factor authentication for additional security",
      "You are responsible for maintaining the security of your account credentials and devices",
      "You must promptly notify us if you suspect unauthorized access to your account",
      "One account per individual — sharing accounts is not permitted",
    ],
  },
  {
    id: "medicare-data",
    title: "5. Medicare Data Connection",
    paragraphs: [
      "The Service offers an optional connection to your Medicare claims data through the official Medicare API. This connection:",
    ],
    items: [
      "Requires your explicit authorization through a secure OAuth process on the official Medicare website",
      "Provides read-only access — we never modify your Medicare records",
      "Can be revoked at any time through your Settings page",
      "Is subject to your consent preferences for AI use, local caching, and analytics",
      "Accesses only Patient, Coverage, and Explanation of Benefits (EOB) data",
      "We never request, access, use, or share your Medicare.gov login credentials — authorization is handled entirely by CMS through secure OAuth",
    ],
    afterItems:
      "Clinical insights such as conditions, medications, and screening history are extracted from your claims data — they are not provided as separate data from Medicare. Your Medicare data is used solely for: (1) displaying your health information to you; (2) providing AI-powered coverage guidance and appeal assistance; and (3) with your explicit consent, personalizing AI conversations. It is not used for any other purpose and is never sold.",
  },
  {
    id: "ai-disclaimer",
    title: "6. AI Disclaimer",
    paragraphs: [
      "All responses are generated by artificial intelligence (Claude via AWS Bedrock). While our AI references real Medicare policies (LCD/NCD), clinical evidence (PubMed), and standardized medical codes, it is not a substitute for professional medical, legal, or financial advice.",
    ],
    items: [
      "AI-generated appeal letters should be reviewed by you and your healthcare provider before submission",
      "Coverage guidance is based on Original Medicare rules — Medicare Advantage plans have their own rules",
      "We do not guarantee that any appeal will be approved or that any claim will be covered",
      "Always verify coverage guidance with your healthcare provider and Medicare",
    ],
  },
  {
    id: "payment-terms",
    title: "7. Payment Terms",
    subsections: [
      {
        title: "Anonymous Access",
        items: [
          "Coverage guidance is available without an account — 1 message per day, no signup required",
          "Anonymous users cannot generate appeal letters or access health data features",
        ],
      },
      {
        title: "Trial",
        items: [
          "Every new account receives a 14-day free trial with 2 messages per day, 1 chat day per week",
          "The free trial does not include appeal letter generation",
          "After the trial period, chat access is locked until you subscribe to a plan",
        ],
      },
      {
        title: "Paid Plans",
        items: [
          "Starter: $10 per month (1 appeal credit, 2 messages/day, 1 chat day/week)",
          "Plus: $20 per month (2 appeal credits, 5 messages/day, 5 chat days/week)",
          "Unlimited: $60 per month (unlimited appeal letters and messages)",
        ],
      },
      {
        title: "Billing",
        items: [
          "Payments are processed by Stripe — we never see or store your credit card number",
          "All subscriptions renew automatically on a monthly basis and can be cancelled at any time",
          "Appeal credits are non-refundable once used to generate an appeal letter",
          "Unused appeal credits do not roll over between monthly billing periods",
        ],
      },
    ],
  },
  {
    id: "acceptable-use",
    title: "8. Acceptable Use",
    paragraphs: ["When using the Service, you agree not to:"],
    items: [
      "Use automated tools to scrape, crawl, or extract data from the Service",
      "Harvest or collect medical codes, policy references, or other structured data for redistribution",
      "Redistribute, resell, or sublicense appeal letters or coverage guidance for commercial purposes",
      "Impersonate another person or misrepresent your identity to access Medicare data",
      "Use the Service to commit fraud or submit false claims to Medicare",
      "Interfere with or disrupt the Service or its infrastructure",
      "Attempt to circumvent rate limits, paywalls, or access controls",
    ],
  },
  {
    id: "intellectual-property",
    title: "9. Intellectual Property",
    items: [
      "Appeal letters generated by the Service are owned by you, the user, and may be freely used for their intended purpose (filing Medicare appeals)",
      "AI-generated content may not be eligible for copyright protection under current law",
      `The ${BRAND.NAME} brand, logo, and original software are the intellectual property of ${BRAND.COMPANY_NAME}`,
      "Medicare policy data, medical codes, and clinical evidence referenced by the Service are from public sources and are not our intellectual property",
    ],
  },
  {
    id: "limitation-of-liability",
    title: "10. Limitation of Liability",
    paragraphs: [
      `${BRAND.NAME} provides Medicare coverage guidance only. To the maximum extent permitted by law:`,
    ],
    items: [
      "We are not responsible for the outcome of any Medicare claim or appeal",
      "We are not liable for decisions made based on our AI-generated guidance",
      "We do not guarantee the accuracy, completeness, or timeliness of coverage information",
      "Our total liability for any claim arising from use of the Service is limited to the amount you paid us in the 12 months preceding the claim",
      "We are not liable for indirect, incidental, consequential, or punitive damages",
    ],
  },
  {
    id: "termination",
    title: "11. Termination",
    items: [
      "You may delete your account at any time through Settings — all your data will be permanently deleted (except audit logs, which are subject to a minimum 6-year HIPAA retention requirement)",
      "We may suspend or terminate accounts that violate these Terms, engage in fraudulent activity, or abuse the Service",
      "Upon termination, your right to use the Service ceases immediately",
      "Sections on limitation of liability, intellectual property, and dispute resolution survive termination",
    ],
  },
  {
    id: "changes",
    title: "12. Changes to These Terms",
    paragraphs: [
      "We may update these Terms from time to time. For material changes, we will notify registered users via email at least 30 days before the new terms take effect, with a summary of what changed. If you disagree with the changes, you may delete your account before the effective date. Continued use of the Service after the effective date constitutes acceptance of the updated Terms.",
      "In the event of a merger, acquisition, or sale of assets, your data may be transferred to a successor entity. We will notify you via email at least 30 days before your data is transferred and becomes subject to different terms. As a holder of CMS Blue Button API production credentials, we will also notify CMS at the earliest practicable time, as production credentials are issued to a specific approved application and entity and a change of ownership requires CMS re-review. You may delete your account and all associated data before the transfer takes effect.",
    ],
  },
  {
    id: "your-data-rights",
    title: "13. Your Medicare Data Rights",
    paragraphs: [
      "As a Medicare beneficiary using the Blue Button APIs through our Service, you have the following rights with respect to your data:",
    ],
    items: [
      "Access: You may view all Medicare data we have stored about you at any time through the Health section of the app",
      "Correction: If you believe data displayed is inaccurate or incomplete, you can refresh your connection to re-sync from the official Medicare source or contact us to flag discrepancies",
      "Deletion: You may delete your account at any time through Settings > Danger Zone — all Medicare data, conversations, appeal letters, and diabetes tracking data are permanently deleted immediately (audit logs recording data access events are retained for a minimum of 6 years per HIPAA requirements)",
      "Revocation: You may disconnect your Medicare connection at any time through Settings — this immediately deletes all cached health data",
      "Consent withdrawal: You may withdraw consent for AI use of your health data at any time through Settings > Privacy & Data",
      "Data portability: You may request a copy of your stored data by contacting us",
    ],
  },
  {
    id: "cms-disclaimer",
    title: "14. CMS Non-Endorsement Disclaimer",
    paragraphs: [
      `This product is not endorsed or certified by the Centers for Medicare & Medicaid Services (CMS) or the U.S. Department of Health and Human Services (HHS). ${BRAND.NAME} is an independent application that accesses Medicare data through publicly available APIs. References to Medicare, CMS, or government programs do not imply any official affiliation, endorsement, or certification.`,
    ],
  },
  {
    id: "contact",
    title: "15. Contact Information",
    paragraphs: [
      "If you have questions about these Terms of Service:",
    ],
    items: [
      "Email: admin@denali.health",
      `Organization: ${BRAND.COMPANY_NAME}`,
    ],
  },
];

interface Section {
  id: string;
  title: string;
  content?: string;
  paragraphs?: string[];
  items?: string[];
  afterItems?: string;
  afterLink?: { href: string; text: string };
  subsections?: {
    title: string;
    items: string[];
  }[];
}

function SectionBlock({ section }: { section: Section }) {
  return (
    <div id={section.id} className="mb-10">
      <h2 className="text-lg font-semibold text-[var(--text-primary)] mb-4 pb-2 border-b border-[var(--border)]">
        {section.title}
      </h2>

      {section.content && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4">
          {section.content}
        </p>
      )}

      {section.paragraphs?.map((p, i) => (
        <p
          key={i}
          className="text-sm text-[var(--text-secondary)] leading-relaxed mb-4"
        >
          {p}
        </p>
      ))}

      {section.items && (
        <ul className="list-disc list-outside pl-5 space-y-2 mb-4">
          {section.items.map((item, i) => (
            <li
              key={i}
              className="text-sm text-[var(--text-secondary)] leading-relaxed"
            >
              {item}
            </li>
          ))}
        </ul>
      )}

      {section.afterItems && (
        <p className="text-sm text-[var(--text-secondary)] leading-relaxed mb-2">
          {section.afterItems}
        </p>
      )}

      {section.afterLink && (
        <Link
          href={section.afterLink.href}
          className="text-sm text-[var(--accent-primary)] hover:underline"
        >
          {section.afterLink.text}
        </Link>
      )}

      {section.subsections?.map((sub, i) => (
        <div key={i} className="mt-4">
          <h3 className="text-sm font-medium text-[var(--text-primary)] mb-2">
            {sub.title}
          </h3>
          <ul className="list-disc list-outside pl-5 space-y-2">
            {sub.items.map((item, j) => (
              <li
                key={j}
                className="text-sm text-[var(--text-secondary)] leading-relaxed"
              >
                {item}
              </li>
            ))}
          </ul>
        </div>
      ))}
    </div>
  );
}

export default function TermsPage() {
  return (
    <>
    <div className="max-w-3xl mx-auto px-4 py-12">
      <h1 className="text-3xl font-bold text-[var(--text-primary)] mb-2">
        Terms of Service
      </h1>
      <p className="text-[var(--text-secondary)] mb-2">
        The rules and conditions for using {BRAND.NAME}.
      </p>
      <p className="text-xs text-[var(--text-muted)] mb-10">
        Effective: {EFFECTIVE_DATE}
      </p>

      {/* Table of Contents */}
      <nav className="mb-10 p-4 rounded-lg bg-[var(--bg-secondary)] border border-[var(--border)]">
        <h2 className="text-sm font-semibold text-[var(--text-primary)] mb-3">
          Contents
        </h2>
        <ol className="list-decimal list-inside space-y-1">
          {SECTIONS.map((section) => (
            <li key={section.id}>
              <a
                href={`#${section.id}`}
                className="text-sm text-[var(--accent-primary)] hover:underline"
              >
                {section.title.replace(/^\d+\.\s/, "")}
              </a>
            </li>
          ))}
        </ol>
      </nav>

      {SECTIONS.map((section) => (
        <SectionBlock key={section.id} section={section} />
      ))}

    </div>
    <LandingFooter />
  </>
  );
}
